url: https://status.narro.co
author: NarroApp
email: support@narro.co
title: Narro Status
description: The status page for the Narro API and services
homepage: https://www.narro.co

permalink: pretty
uptime_days: 60

# TODO: Build pagination into archive
gems: [jekyll-paginate]
paginate: 2
paginate_path: '/archive/page:num/'
